CREATE TABLE DOSEN (
    ID_DOSEN INT PRIMARY KEY,
    NAMA_DOSEN VARCHAR(100),
    EMAIL_DOSEN VARCHAR(100)
);

CREATE TABLE KULIAH (
    ID_KULIAH INT PRIMARY KEY,
    NAMA_KULIAH VARCHAR(100),
    SKS INT,
    ID_DOSEN INT,
    FOREIGN KEY (ID_DOSEN) REFERENCES DOSEN(ID_DOSEN)
);
